#!/bin/bash

echo "Installing python dependencies...";
pip install -r requirements.txt;

pip install -r test-requirements.txt;

pip install -e .;

echo "Installing node dependencies...";
npm install;

if [ "$1" == '--hooks' ]; then
    echo "Installing pre-commit and pre-commit hooks";
    pip install pre-commit;
    pre-commit install;
fi
