import React from 'react';
import styles from './openletter.module.css';

const OpenLetter = () => {
    return (
        <main id="mainContent">
            <div className={`${styles.contentSize} p-5`}>
                <h4>To the University of Ottawa Administration,</h4>
                <p>I understand that assessing students during distance learning is a nuanced issue. The University has a lot of factors to consider, especially as it pertains to academic integrity of its students, and the several cases that came out of the Winter 2020 final exam period does show cause for alarm. However, I think that, in large part, it speaks to the archaic nature of modern educational assessments.</p>
                <p>Before going into that, though, there are a lot of reasons why the proctoring software worries me; so many, in fact, that detailing all of them would be unreasonable to do in a single letter. I&#39;ll focus on two key concerns that I think are significant enough to justify the ban of this software, even if it would mean a repeat of the events that lead to the Winter semester&#39;s difficulties:</p>
                <p>The first is a matter of ableist discrimination. Specifically, the use of video monitoring software for examinations which use AI (though it is applicable for even those who utilize live proctors) provide a very harmful classification of students with disabilities as &#39;probably cheating&#39;. For any student with ADHD, or similar conditions that affects attention span, the rate of false-positives will necessarily be high, as the benchmarks used - looking away from the screen for a few seconds repeatedly - are also symptoms of these disabilities. This culture of culpability adds another barrier, real or assumed, for students with disabilities.</p>
                <p>Even more troubling is how this might impact students with physical health problems that are unable to excuse themselves for legitimate health needs. One very graphic example was outlined in a Washington Post article on April 1, 2020: <a href="https://www.washingtonpost.com/technology/2020/04/01/online-proctoring-college-exams-coronavirus/">Mass school closures in the wake of the coronavirus are driving a new wave of student surveillance</a></p>
                <div className="pl-4 pr-5">
                <p>&quot;When University of Florida sophomore Cheyenne Keating felt a rush of nausea a few weeks ago during her at-home statistics exam, she looked into her webcam and asked the stranger on the other side: Is it okay to throw up at my desk?</p>
                <p>He said yes. So halfway through the two-hour test, during which her every movement was scrutinized for cheating and no bathroom breaks were permitted, she vomited into a wicker basket, dabbed the mess with a blanket and got right back to work. The stranger saw everything. When the test was finished, he said she was free to log off. Only then could she clean herself up.&quot;</p>
                </div>
                <p>Many other common health conditions would be impacted by this, and one major concern I have is whether the university will have the proper resources to deal with these implications, exceptions, and necessary accommodations by enforcing the proctoring software. Even beyond that, this software has troubling implications for students who menstruate, regardless of other health conditions. Should a student unexpectedly begin their menstrual cycle mid-exam, these softwares would force students to make a critical decision similar to one that Cheyenne Keating&#39;s: should they stay in a physically uncomfortable condition, or should they risk failing their exam and having their academic integrity called into question? Even if these students are able to get remediation, this places an undue and unreasonable burden upon students by assuming that they are cheating. Many other common circumstances can also have similar problems with this software, such as for students who are also parents, who have roommates, etc.</p>
                <p>The second concern is also related to accessibility, but in a different form. Some discussion that I have seen about this - including conversations I was informed occurred in some classes - acknowledged the implications to digital privacy of the Respondus Monitor software (and similar video monitoring software for proctoring), but opted to still utilize the Lockdown browser. It is exceedingly common for students to have multiple devices available, either through roommates, personal cell phones, work machines, etc., which makes the Lockdown browser ineffectual at preventing real instances of cheating by looking up material on search engines or searching through notes for the majority of students. Instead, this would only create a system in which any student that is able to afford multiple devices can circumvent the illusion of integrity that is offered through Lockdown and similar software. This, in turn, disproportionately benefits students who can afford a secondary internet-connected device without reducing tangible issues of academic fraud. More plainly speaking, this amounts to classist discrimination.</p>
                <p>These two cases, I think, illustrate how this software will do harm for students to such a point where even not altering the assessment process is a better solution. However, since it would be irresponsible of the university to accept violations of academic integrity, there are still options that the university can pursue. Thankfully there is a lot of discussion and writing surrounding this, as more and more universities adopt proctoring software and alternatives. In particular, one article I really liked goes on to say the following:</p>
                <div className="pl-4 pr-5">
                <p>Faculty and administrators concerned with student privacy and security in addition to academic integrity need to consider alternative options for assessment of student performance. One is to abandon traditional exams where possible and offer alternative forms of graded work. This might require more time grading and providing feedback on the part of instructors. But it might be a tradeoff that some instructors are willing and able to make.</p>
                <p>For others teaching classes for which that is not possible, instructors might consider making exams open book or just trusting students to do the right thing. Though it pains me to say it, if students cheat, they are the ones who are losing out in the long run.</p>
                <p>Finally instructors might consider proctoring the exams themselves using tools like Zoom. But, then again, these tools have their own tradeoffs in terms of ease of use, privacy, security, and access to webcams and stable internet connections.</p>
                <p>There are no easy answers. One of my fall courses will be a large lecture that is primarily exam based. If my university ends up remaining online like some others, I too will be faced with making hard choices about how to assess student learning in a way that is fair, equitable, and respectful of student privacy and security. Despite the difficulty, I believe that these are values that are worth upholding.</p>
                </div>
                <p><a href="https://www.forbes.com/sites/seanlawson/2020/04/24/are-schools-forcing-students-to-install-spyware-that-invades-their-privacy-as-a-result-of-the-coronavirus-lockdown/#25b8a580638d">Are Schools Forcing Students To Install Spyware That Invades Their Privacy As A Result Of The Coronavirus Lockdown?</a>, Sean Lawson, Apr 24 2020</p>
                <p>We are at an unprecedented time in modern history, both in the scope of the current pandemic crisis and the rate of advancement we have done technologically in the last 100 years. I have long felt, personally, that the way in which we assess and educate students is inadequate for the digital age where information is so easily accessible. Increasing the focus on projects, labs, and open book/take home exams would be a better measure of student performance and understanding while simultaneously being a better reflection of the modern workforce that universities purport to prepare us for. </p>
                <br />
                <p>Sincerely,</p>
                <p>Natalia Maximo<br />
                Computer Science student<br />
                University of Ottawa</p>
            </div>
        </main>
    )
}
export default OpenLetter
